server:
  port: 9295

spring:
  application:
    name: HYSTRIX-DASHBOARD
  main:
    allow-circular-references: true

hystrix:
  dashboard:
    proxy-stream-allow-list: "*"


management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream, info, health
        
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost  
 